spring:
  datasource:
    username: root
    password: Jay49904211
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/concordia?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
  http:
    multipart:
      enabled: true
server:
  port: 8877